repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
    -   id: ruff
        args: [--fix, --unsafe-fixes]
        # Solo verificar archivos modificados
        files: ^scripts/utils/.*\.py$
    -   id: ruff-format
        files: ^scripts/utils/.*\.py$
